apiVersion: pipecd.dev/v1beta1
kind: Piped
spec:
  projectID: your-project
  pipedID: your-piped-id
  pipedKeyFile: /etc/piped-secret/key
  apiAddress: your-control-plane:443
  
  repositories:
    - repoId: examples
      remote: https://github.com/pipe-cd/examples.git
      branch: master
  
  plugins:
    - name: kubernetes
      port: 7001
      url: https://github.com/pipe-cd/pipecd/releases/download/v1.0.0-rc0/plugin-kubernetes-linux-amd64
      deployTargets:
        - name: dev
          config:
            kubectlVersion: 1.33.0
            kubeConfigPath: ~/.kube/config
