apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
        pipecd.dev/variant: primary
    spec:
      containers:
        - name: app
          image: nginx:1.25
          ports:
            - containerPort: 80
